/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package hu.simplexion.z2.rui

/**
 * Interface to implement by fragments generated by the compiler plugin.
 * This interface may define functions the generated fragments use, so
 * we do not have to code them in IR.
 */
@RuiPublicApi
interface RuiGeneratedFragment<BT> : RuiFragment<BT> {

    val ruiFragment: RuiFragment<BT>

    override fun ruiCreate() {
        ruiFragment.ruiCreate()
    }

    override fun ruiMount(bridge: RuiBridge<BT>) {
        ruiFragment.ruiMount(bridge)
    }

    // do not override ruiPatch, it should be generated in all cases

    override fun ruiUnmount(bridge: RuiBridge<BT>) {
        ruiFragment.ruiUnmount(bridge)
    }

    override fun ruiDispose() {
        ruiFragment.ruiDispose()
    }

}