/*
 * Copyright © 2020-2021, Simplexion, Hungary and contributors. Use of this source code is governed by the Apache 2.0 license.
 */
package hu.simplexion.z2.rui

/**
 * Interface to implement by fragments generated by the compiler plugin.
 * This interface may define functions the generated fragments use, so
 * we do not have to code them in IR.
 */
@RuiPublicApi
interface RuiGeneratedFragment<BT> : RuiFragment<BT> {

    /**
     * The top level fragment of this scope. This may be:
     *
     * - a structural fragment such as block, when or a loop
     * - direct call to another rui function
     *
     * Set to [RuiFragment.ruiClosure] by the initializer of the class
     * that implements [RuiGeneratedFragment].
     */
    val containedFragment: RuiFragment<BT>

    override fun ruiCreate() {
        containedFragment.ruiCreate()
    }

    override fun ruiMount(bridge: RuiBridge<BT>) {
        containedFragment.ruiMount(bridge)
    }

    // do not override ruiPatch, it should be generated in all cases

    override fun ruiUnmount(bridge: RuiBridge<BT>) {
        containedFragment.ruiUnmount(bridge)
    }

    override fun ruiDispose() {
        containedFragment.ruiDispose()
    }

}