package hu.simplexion.z2.browser

import hu.simplexion.z2.commons.i18n.LocalizedTextStore

object browserStrings : LocalizedTextStore() {
    val actions by "műveletek"
    val add by "hozzáadás"
    val back by "vissza"
    val cancel by "mégse"
    val discardChanges by "Discard changes?"
    val discardChangesMessage by "To save the changes click on cancel and save the changes before leaving the page."
    val edit by "szerkesztés"
    val export by "export"
    val name by "név"
    val no by "nem"
    val open by "megnyitás"
    val searchHint by "keresés"
    val settings by "beállítások"
    val yes by "igen"
    val _empty by ""
    val createdBy by "létrehozó"
    val createdAt by "létrehozás"
    val content by "tartalom"
    val details by "részletek"
    val ok by "rendben"
    val previous by "előző"
    val next by "következő"
    val searchInProgress by "...keresés..."
    val noHits by "nincs találat"
    val dropFileHere by "dobja ide a fájlt vagy klikkeljen a kiválasztáshoz"
    val dropAttachmentHere by "dobja ide a mellékleteket vagy klikkeljen a kiválasztáshoz"
    val fileAlreadyAdded by "Ilyen nevű fájl már hozzá van adva."
    val selectMainFirst by "A mellékletek kiválasztása előtt a fájl ki kell választani."
    val selectFolderFirst by "Válasszon mappát!"
    val zeroBytes by "0 bájt"
    val bytes by "bájt"
    val noFilesSelected by "nincs fájl kiválasztva"
    val filesSelected by "fájl"
    val type by "Típus"
    val bundleNameSupport by "a dokumentum címe"
    val title by "Cím"
    val file by "Fájl"
    val attachments by "Mellékletek"
    val folder by "Mappa"
}