

package hu.simplexion.z2.schematic.kotlin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link hu.simplexion.z2.schematic.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("defaults.kt")
    public void testDefaults() throws Exception {
        runTest("testData/box/defaults.kt");
    }

    @Test
    @TestMetadata("getAndSet.kt")
    public void testGetAndSet() throws Exception {
        runTest("testData/box/getAndSet.kt");
    }

    @Test
    @TestMetadata("newInstance.kt")
    public void testNewInstance() throws Exception {
        runTest("testData/box/newInstance.kt");
    }

    @Test
    @TestMetadata("proto.kt")
    public void testProto() throws Exception {
        runTest("testData/box/proto.kt");
    }

    @Test
    @TestMetadata("saf.kt")
    public void testSaf() throws Exception {
        runTest("testData/box/saf.kt");
    }

    @Test
    @TestMetadata("schematicField.kt")
    public void testSchematicField() throws Exception {
        runTest("testData/box/schematicField.kt");
    }

    @Test
    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        runTest("testData/box/simple.kt");
    }

    @Test
    @TestMetadata("typeArgument.kt")
    public void testTypeArgument() throws Exception {
        runTest("testData/box/typeArgument.kt");
    }

    @Test
    @TestMetadata("types.kt")
    public void testTypes() throws Exception {
        runTest("testData/box/types.kt");
    }
}
