

package hu.simplexion.z2.service.kotlin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link hu.simplexion.z2.service.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("basic.kt")
    public void testBasic() throws Exception {
        runTest("testData/box/basic.kt");
    }

    @Test
    @TestMetadata("context.kt")
    public void testContext() throws Exception {
        runTest("testData/box/context.kt");
    }

    @Test
    @TestMetadata("direct.kt")
    public void testDirect() throws Exception {
        runTest("testData/box/direct.kt");
    }

    @Test
    @TestMetadata("serviceName.kt")
    public void testServiceName() throws Exception {
        runTest("testData/box/serviceName.kt");
    }

    @Test
    @TestMetadata("types.kt")
    public void testTypes() throws Exception {
        runTest("testData/box/types.kt");
    }
}
